ccflags-y := -Ofast -fgcse-lm -fgcse-sm -fsched-spec-load -fforce-addr -ffast-math -fsingle-precision-constant -marm -march=armv7-a -mcpu=cortex-a9 -mtune=cortex-a15 -mfpu=neon -funsafe-math-optimizations -ftree-vectorize -mvectorize-with-neon-quad

obj-y += msm_ion.o ion_cp_common.o
